### ISSUE TITLE
Can't find additionaldataenabled Boolean, where do I set it?

### ISSUE THREAD

**Issue by adamtj12** [payleven/mPOS-SDK-iOS#4]

**Comment by konradfeketepayleven** [comment]
Dear Adam,

Just for the record - as this has been sorted via mail - your developer account is now enabled for additional data. This gets only (manually) enabled by payleven if you, as an integrator, wish the create your own payment receipts. As agreed please send us the requested example receipts so that payleven can audit them. 
Thank you in advance!
